name: Rust workflow

on: push

jobs:
  rust-wf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Look for vulnerabilities
        uses: icepuma/rust-action@master 
        with:
          args: cargo audit 

      - name: Check code format
        uses: icepuma/rust-action@master 
        with:
          args: cargo fmt -- --check

      - name: Cargo clippy
        uses: icepuma/rust-action@master
        with:
          args: cargo clippy
          # args: cargo clippy -- -Dwarnings
      
      - name: Cargo test
        uses: icepuma/rust-action@master
        with:
          args: cargo test
