name: Rust workflow

on: push

jobs:
  rust-wf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -Dwarnings
      
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
