name: Rust workflow

on: push

jobs:
  rust-wf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -Dwarnings
      
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository}}:latest

      - name: Docker image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
